export const INTEGRATION_ARTIFACTS_SCHEMA =
	"urn:graphrefly-stack:schema:integration-artifacts:v1" as const;
export const INTEGRATION_GOLDEN_SUITE_SCHEMA =
	"urn:graphrefly-stack:schema:integration-golden-suite:v1" as const;

export const INTEGRATION_CANDIDATE_SCHEMA = "graphrefly.stack.integration-candidate.v1" as const;
export const INTEGRATION_RESULT_SCHEMA = "graphrefly.stack.integration-result.v1" as const;

export const INTEGRATION_REASON_ORDER = [
	"ANCESTRY_AMBIGUOUS",
	"HEAD_RANGE_NON_LINEAR",
	"TARGET_MOVED",
	"HEAD_MOVED",
	"TEXT_CONFLICT",
	"CANDIDATE_EVALUATION_FAILED",
	"CANDIDATE_BLUEPRINT_INVALID",
	"NODE_DELETE_CHANGE",
	"NODE_INCOMPATIBLE_CHANGE",
	"EDGE_INCOMPATIBLE_CHANGE",
	"SUBGRAPH_INCOMPATIBLE_CHANGE",
	"METADATA_INCOMPATIBLE_CHANGE",
	"CLAIM_INVALIDATED",
	"DEPENDENCY_INVALIDATED",
	"POLICY_INVALIDATED",
	"HEAD_GATE_NOT_PASSING",
	"ARTIFACT_TAMPERED",
] as const;

export type IntegrationReasonCode = (typeof INTEGRATION_REASON_ORDER)[number];

export const INTEGRATION_CONFLICT_REASONS = [
	"TEXT_CONFLICT",
	"CANDIDATE_BLUEPRINT_INVALID",
	"NODE_DELETE_CHANGE",
	"NODE_INCOMPATIBLE_CHANGE",
	"EDGE_INCOMPATIBLE_CHANGE",
	"SUBGRAPH_INCOMPATIBLE_CHANGE",
	"METADATA_INCOMPATIBLE_CHANGE",
	"CLAIM_INVALIDATED",
	"DEPENDENCY_INVALIDATED",
	"POLICY_INVALIDATED",
	"HEAD_GATE_NOT_PASSING",
] as const satisfies readonly IntegrationReasonCode[];
